sudo: false
language: ruby
rvm:
  - 2.1.2
bundler_args: --without development --without kitchen_vagrant
cache: bundler
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
gemfile:
  - Gemfile
script:
  - bundle exec rake travis
